import { PADDLE_BUYER_SUPPORT_URL } from '@/lib/brand';
import type { LegalLocale, LegalSeller } from '@/lib/legal';

export type LegalPolicyKind = 'privacy' | 'terms' | 'refund';

export function policyMetadata(kind: LegalPolicyKind, locale: LegalLocale) {
  const values = {
    en: {
      privacy: ['Privacy Policy', 'How Syncmemos collects, uses, shares, retains, and protects personal data.'],
      terms: ['Terms of Service', 'The rules for using Syncmemos and purchasing a recurring subscription.'],
      refund: ['Refund Policy', 'The commercial 14-day money-back guarantee, cancellation, and statutory rights.'],
    },
    sv: {
      privacy: ['Integritetspolicy', 'Så samlar Syncmemos in, använder, delar, lagrar och skyddar personuppgifter.'],
      terms: ['Användarvillkor', 'Reglerna för att använda Syncmemos och köpa ett återkommande abonnemang.'],
      refund: ['Återbetalningspolicy', 'Den kommersiella 14-dagarsgarantin, uppsägning och lagstadgade rättigheter.'],
    },
  } as const;
  const [title, description] = values[locale][kind];
  return { title, description };
}

export function PolicyContent({ kind, locale, seller }: {
  kind: LegalPolicyKind;
  locale: LegalLocale;
  seller: LegalSeller;
}) {
  if (locale === 'sv') {
    if (kind === 'privacy') return <SwedishPrivacy seller={seller} />;
    if (kind === 'terms') return <SwedishTerms seller={seller} />;
    return <SwedishRefund seller={seller} />;
  }
  if (kind === 'privacy') return <EnglishPrivacy seller={seller} />;
  if (kind === 'terms') return <EnglishTerms seller={seller} />;
  return <EnglishRefund seller={seller} />;
}

function EnglishPrivacy({ seller }: { seller: LegalSeller }) {
  return <>
    <section><h2>1. Who is responsible</h2><p>{seller.name} is the controller for the personal data Syncmemos processes to provide the application. Paddle is an independent controller for checkout, payment, tax, receipt, and buyer-support processing under its own privacy notice.</p></section>
    <section><h2>2. Data we process</h2><ul><li>Account and authentication data, including email address, profile identity, verification status, sessions, and security events.</li><li>Meeting data, including meeting links, participant information supplied by providers, recordings, audio, transcripts, summaries, documents, chat prompts, and generated responses.</li><li>Usage and support data, including plan usage, feature interactions, messages to support, IP address, device and request metadata, and diagnostic events.</li><li>Billing data shared by Paddle, including Paddle customer, transaction, price, and subscription identifiers and status. Syncmemos does not receive full card details.</li></ul></section>
    <section><h2>3. Sources and purposes</h2><p>We receive data from you, other meeting participants through a recording you initiate, Google authentication, meeting and transcription providers, Paddle, and normal use of the service. We process it to create and manage accounts, join or record meetings at your request, transcribe and generate requested content, answer support requests, administer subscriptions, prevent abuse, secure and troubleshoot the service, and meet legal obligations.</p></section>
    <section><h2>4. Legal bases</h2><ul><li><strong>Contract:</strong> account administration and the processing needed to provide features you request.</li><li><strong>Legitimate interests:</strong> securing, debugging, protecting, and operating the service, provided those interests are not overridden by individual rights.</li><li><strong>Legal obligation:</strong> records and responses that applicable law requires us to keep or provide.</li><li><strong>Consent:</strong> only where we separately ask for consent; it can be withdrawn without affecting earlier lawful processing.</li></ul><p>The in-app recording confirmation does not replace the organiser&apos;s responsibility to establish a lawful basis and give all required notices to participants.</p></section>
    <section><h2>5. Providers and transfers</h2><p>Depending on the feature and deployed configuration, data may be processed by Railway, Vercel, Supabase, Recall, AssemblyAI, Google (including Gemini and OAuth), Anthropic, Resend, Sentry, and Paddle. Providers may process data outside Sweden or the EEA. We do not claim complete EU data residency. Applicable transfer safeguards and provider settings must be verified before a provider is enabled in production.</p></section>
    <section><h2>6. Retention and deletion</h2><ul><li>Meeting audio becomes eligible for deletion one hour after transcription and is deleted by the next six-hour sweep, so actual application-side retention is normally between roughly one and seven hours after transcription.</li><li>Live transcript segments are replaced when the final transcript is stored.</li><li>Sessions are retained for up to 30 days; the email-send ledger for 30 days; verification tokens for up to 24 hours plus the next sweep.</li><li>Transcripts, documents, chat, and usage data remain until account deletion unless an earlier deletion applies.</li></ul><p>Provider logs, backups, fraud records, and Paddle&apos;s statutory transaction records follow the relevant provider&apos;s obligations and retention. Account deletion removes application data under Syncmemos&apos; control, subject to legal exceptions and provider completion times.</p></section>
    <section><h2>7. Your choices and rights</h2><p>Subject to applicable law, you may request access, correction, deletion, restriction, portability, or object to processing based on legitimate interests. You may also complain to the Swedish Authority for Privacy Protection (IMY). We may need information to verify your identity before acting on a request.</p></section>
    <section><h2>8. Security, children, and changes</h2><p>We use access controls, encrypted transport, hashed session and verification secrets, short audio retention, and provider deletion requests. No internet service is risk-free. Syncmemos is not directed to children. Material policy changes will be presented with a new effective date and, where required, additional notice.</p></section>
    <section><h2>9. Contact</h2><p>Send privacy requests to <a href={`mailto:${seller.email}`}>{seller.email}</a>. Do not send passwords, identity documents, recordings, or other sensitive material unless we provide a secure method.</p></section>
  </>;
}
function SwedishPrivacy({ seller }: { seller: LegalSeller }) {
  return <>
    <section><h2>1. Vem är ansvarig</h2><p>{seller.name} är personuppgiftsansvarig för de personuppgifter som Syncmemos behandlar för att tillhandahålla applikationen. Paddle är självständigt personuppgiftsansvarig för behandling som rör kassa, betalning, skatt, kvitto och köparsupport enligt sin egen integritetspolicy.</p></section>
    <section><h2>2. Uppgifter vi behandlar</h2><ul><li>Konto- och autentiseringsuppgifter, såsom e-postadress, profilidentitet, verifieringsstatus, sessioner och säkerhetshändelser.</li><li>Mötesuppgifter, såsom möteslänkar, deltagarinformation från leverantörer, inspelningar, ljud, transkript, sammanfattningar, dokument, chattfrågor och genererade svar.</li><li>Användnings- och supportuppgifter, såsom plananvändning, funktionsinteraktioner, supportmeddelanden, IP-adress, enhets- och anropsmetadata samt diagnostikhändelser.</li><li>Betalningsrelaterade uppgifter från Paddle, såsom Paddle-id och status för kund, transaktion, pris och abonnemang. Syncmemos tar inte emot fullständiga kortuppgifter.</li></ul></section>
    <section><h2>3. Källor och ändamål</h2><p>Vi får uppgifter från dig, andra mötesdeltagare genom en inspelning du initierar, Google-inloggning, mötes- och transkriberingsleverantörer, Paddle och normal användning av tjänsten. Vi behandlar dem för att hantera konton, ansluta till eller spela in möten på din begäran, transkribera och skapa begärt innehåll, ge support, administrera abonnemang, motverka missbruk, säkra och felsöka tjänsten samt uppfylla rättsliga skyldigheter.</p></section>
    <section><h2>4. Rättsliga grunder</h2><ul><li><strong>Avtal:</strong> kontohantering och behandling som behövs för att tillhandahålla funktioner du begär.</li><li><strong>Berättigat intresse:</strong> att säkra, felsöka, skydda och driva tjänsten, när individens rättigheter inte väger tyngre.</li><li><strong>Rättslig förpliktelse:</strong> uppgifter och svar som tillämplig lag kräver att vi sparar eller lämnar.</li><li><strong>Samtycke:</strong> endast när vi frågar separat; det kan återkallas utan att tidigare laglig behandling påverkas.</li></ul><p>Inspelningsbekräftelsen i appen ersätter inte organisatörens ansvar att ha rättslig grund och informera deltagarna enligt gällande regler.</p></section>
    <section><h2>5. Leverantörer och överföringar</h2><p>Beroende på funktion och driftskonfiguration kan uppgifter behandlas av Railway, Vercel, Supabase, Recall, AssemblyAI, Google (inklusive Gemini och OAuth), Anthropic, Resend, Sentry och Paddle. Leverantörer kan behandla uppgifter utanför Sverige eller EES. Vi påstår inte fullständig EU-datalagring. Tillämpliga överföringsskydd och leverantörsinställningar måste verifieras innan en leverantör aktiveras i produktion.</p></section>
    <section><h2>6. Lagring och radering</h2><ul><li>Mötesljud blir raderingsbart en timme efter transkribering och tas bort vid nästa sex-timmarssvep. Faktisk lagring i applikationen är därför normalt ungefär en till sju timmar efter transkribering.</li><li>Live-segment ersätts när det slutliga transkriptet sparas.</li><li>Sessioner sparas upp till 30 dagar, e-postloggen 30 dagar och verifieringstoken upp till 24 timmar plus nästa svep.</li><li>Transkript, dokument, chatt och användningsdata finns kvar tills kontot raderas om inte tidigare radering gäller.</li></ul><p>Leverantörsloggar, säkerhetskopior, bedrägeriregister och Paddles lagstadgade transaktionsregister följer respektive leverantörs skyldigheter och lagring. Kontoradering tar bort applikationsdata under Syncmemos kontroll, med förbehåll för rättsliga undantag och leverantörernas slutförandetider.</p></section>
    <section><h2>7. Dina val och rättigheter</h2><p>Med de begränsningar som följer av lag kan du begära tillgång, rättelse, radering, begränsning eller dataportabilitet samt invända mot behandling som grundas på berättigat intresse. Du kan också klaga hos Integritetsskyddsmyndigheten (IMY). Vi kan behöva uppgifter för att kontrollera din identitet innan en begäran genomförs.</p></section>
    <section><h2>8. Säkerhet, barn och ändringar</h2><p>Vi använder åtkomstkontroller, krypterad överföring, hashade sessions- och verifieringshemligheter, kort ljudlagring och begäran om radering hos leverantörer. Ingen internettjänst är riskfri. Syncmemos riktar sig inte till barn. Väsentliga ändringar publiceras med nytt ikraftträdandedatum och, när det krävs, ytterligare information.</p></section>
    <section><h2>9. Kontakt</h2><p>Skicka integritetsbegäran till <a href={`mailto:${seller.email}`}>{seller.email}</a>. Skicka inte lösenord, identitetshandlingar, inspelningar eller annat känsligt material om vi inte har anvisat en säker metod.</p></section>
  </>;
}

function EnglishTerms({ seller }: { seller: LegalSeller }) {
  return <>
    <section><h2>1. Agreement and eligibility</h2><p>These Terms govern access to Syncmemos, supplied by {seller.name}. By creating an account or using the service, you agree to these Terms. You must be legally able to enter this agreement and provide accurate account information. If you use Syncmemos for an organisation, you confirm that you may bind it.</p></section>
    <section><h2>2. The service</h2><p>Syncmemos can join supported online meetings or accept an in-room recording, create transcripts and AI-generated meeting content, and let account holders search and discuss that content. AI output can be incomplete or wrong and must be reviewed before it is relied on. Feature limits and supported integrations are described in the product and pricing pages.</p></section>
    <section><h2>3. Recording responsibility</h2><p>You may only record, upload, or process a meeting when you have the necessary authority and lawful basis. You are responsible for giving all required notices, obtaining any required consent, respecting workplace rules, and stopping a recording when required. The in-app confirmation records no legal acceptance version and does not transfer that responsibility to Syncmemos.</p></section>
    <section><h2>4. Acceptable use</h2><p>You must not use Syncmemos unlawfully; infringe privacy, confidentiality, employment, intellectual-property, or publicity rights; submit malicious code; bypass limits or security; probe other accounts; resell access without permission; or use outputs to make solely automated decisions with legal or similarly significant effects about a person.</p></section>
    <section><h2>5. Your content and our service</h2><p>You retain rights in content you lawfully submit. You grant us the limited rights needed to host, transmit, transcribe, generate, secure, and delete that content to provide the service. We and our licensors retain rights in Syncmemos software, design, and branding. Feedback may be used without identifying you or disclosing your confidential content.</p></section>
    <section><h2>6. Plans, Paddle, and renewal</h2><p>Free and paid plan limits appear on the pricing page. Paid subscriptions renew automatically for the selected monthly or annual period at the price shown before checkout until canceled. Team prices are per seat. Applicable tax is calculated at checkout.</p><p>Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides payment-related customer service and handles returns. Paddle&apos;s Buyer Terms and Privacy Notice also apply to the transaction.</p></section>
    <section><h2>7. Cancellation, withdrawal, and refunds</h2><p>You can stop the next renewal through Settings and the Paddle Customer Portal. Cancellation does not normally end the already paid period. To exercise a statutory withdrawal right or request a refund, use the Paddle Buyer Support route linked from Settings and the Refund Policy. Paddle receives and handles these requests as Merchant of Record under its Buyer Terms and Refund Policy. Submitting a request is not itself approval. The separate Refund Policy also explains our first-purchase 14-day money-back guarantee. Mandatory consumer rights always apply and are not reduced by these Terms or the commercial guarantee.</p></section>
    <section><h2>8. Availability and account closure</h2><p>We may change or discontinue features, apply reasonable limits, or suspend access to protect users, providers, or the service. You may delete your account in Settings. We may close an account for material or repeated breach, legal requirements, security risk, or non-payment, with notice where reasonably possible.</p></section>
    <section><h2>9. Disclaimers and liability</h2><p>Syncmemos is provided with reasonable care but without a promise that it will be uninterrupted or error-free. It is not legal, HR, medical, financial, or other professional advice. Nothing in these Terms excludes liability or remedies that cannot lawfully be excluded. Subject to mandatory law, neither party is liable for indirect or consequential loss that was not reasonably foreseeable.</p></section>
    <section><h2>10. Law, changes, and contact</h2><p>Swedish law governs these Terms, without removing mandatory protections available to consumers in their country of residence. Material changes will be notified as required and apply prospectively. Contact <a href={`mailto:${seller.email}`}>{seller.email}</a> with questions.</p></section>
  </>;
}

function SwedishTerms({ seller }: { seller: LegalSeller }) {
  return <>
    <section><h2>1. Avtal och behörighet</h2><p>Dessa villkor gäller för Syncmemos, som tillhandahålls av {seller.name}. Genom att skapa ett konto eller använda tjänsten godkänner du villkoren. Du måste kunna ingå avtalet rättsligt och lämna korrekta kontouppgifter. Om du använder Syncmemos för en organisation bekräftar du att du får binda den.</p></section>
    <section><h2>2. Tjänsten</h2><p>Syncmemos kan ansluta till stödda onlinemöten eller ta emot en inspelning i rummet, skapa transkript och AI-genererat mötesinnehåll samt låta kontoinnehavaren söka och samtala om innehållet. AI-resultat kan vara ofullständiga eller felaktiga och måste granskas innan de används som underlag. Funktionsgränser och integrationer beskrivs i produkten och på prissidan.</p></section>
    <section><h2>3. Ansvar för inspelning</h2><p>Du får bara spela in, ladda upp eller behandla ett möte när du har nödvändig behörighet och rättslig grund. Du ansvarar för all information och alla samtycken som krävs, arbetsplatsregler och att stoppa inspelningen när det behövs. Bekräftelsen i appen sparar ingen juridisk acceptansversion och flyttar inte ansvaret till Syncmemos.</p></section>
    <section><h2>4. Tillåten användning</h2><p>Du får inte använda Syncmemos olagligt; kränka integritet, sekretess, arbetsrätt, immateriella rättigheter eller personlighetsrätt; skicka skadlig kod; kringgå gränser eller säkerhet; undersöka andra konton; sälja åtkomst vidare utan tillstånd; eller använda resultat för helt automatiserade beslut med rättsliga eller liknande betydande följder för en person.</p></section>
    <section><h2>5. Ditt innehåll och vår tjänst</h2><p>Du behåller rättigheterna till innehåll som du lagligen lämnar. Du ger oss de begränsade rättigheter som krävs för att lagra, överföra, transkribera, generera, säkra och radera innehållet för att leverera tjänsten. Vi och våra licensgivare behåller rättigheterna till Syncmemos programvara, design och varumärke. Feedback kan användas utan att identifiera dig eller röja konfidentiellt innehåll.</p></section>
    <section><h2>6. Planer, Paddle och förnyelse</h2><p>Gränser för gratis- och betalplaner visas på prissidan. Betalabonnemang förnyas automatiskt månadsvis eller årsvis till priset som visas före köp tills de sägs upp. Teampriser gäller per plats. Tillämplig skatt beräknas i kassan.</p><p>Vår beställningsprocess genomförs av vår onlineåterförsäljare Paddle.com. Paddle.com är Merchant of Record för alla våra beställningar. Paddle ger betalningsrelaterad kundservice och hanterar återbetalningar. Paddles köparvillkor och integritetsinformation gäller också för transaktionen.</p></section>
    <section><h2>7. Uppsägning, ånger och återbetalning</h2><p>Du kan stoppa nästa förnyelse via Inställningar och Paddles kundportal. Uppsägning avslutar normalt inte den redan betalda perioden. För att utöva lagstadgad ångerrätt eller begära återbetalning använder du Paddles köparsupport som länkas från Inställningar och återbetalningspolicyn. Paddle tar emot och handlägger dessa begäranden som Merchant of Record enligt sina köparvillkor och sin återbetalningspolicy. Att skicka en begäran innebär inte i sig att den har godkänts. Den separata återbetalningspolicyn beskriver också vår 14-dagarsgaranti för första köpet. Tvingande konsumenträttigheter gäller alltid och begränsas inte av dessa villkor eller den kommersiella garantin.</p></section>
    <section><h2>8. Tillgänglighet och kontoavslut</h2><p>Vi kan ändra eller sluta erbjuda funktioner, införa rimliga gränser eller stänga av åtkomst för att skydda användare, leverantörer eller tjänsten. Du kan radera kontot i Inställningar. Vi kan avsluta ett konto vid väsentliga eller upprepade brott, rättsliga krav, säkerhetsrisk eller utebliven betalning, med underrättelse när det rimligen är möjligt.</p></section>
    <section><h2>9. Friskrivning och ansvar</h2><p>Syncmemos tillhandahålls med skälig omsorg men utan löfte om oavbruten eller felfri drift. Tjänsten är inte juridisk, HR-, medicinsk, ekonomisk eller annan professionell rådgivning. Inget i villkoren utesluter ansvar eller rättsmedel som enligt lag inte får uteslutas. Med förbehåll för tvingande lag ansvarar ingen part för indirekt skada eller följdskada som inte rimligen kunde förutses.</p></section>
    <section><h2>10. Lag, ändringar och kontakt</h2><p>Svensk lag gäller utan att tvingande skydd för konsumenter i deras bosättningsland tas bort. Väsentliga ändringar meddelas när det krävs och gäller framåt. Kontakta <a href={`mailto:${seller.email}`}>{seller.email}</a> vid frågor.</p></section>
  </>;
}

function EnglishRefund({ seller }: { seller: LegalSeller }) {
  return <>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6" aria-labelledby="exercise-withdrawal-right">
      <h2 id="exercise-withdrawal-right">Exercise a statutory withdrawal right</h2>
      <p>A statutory withdrawal is not the same as a voluntary refund. Open Paddle Buyer Support, identify yourself with the email address used for the purchase, and choose the option for withdrawing from the purchase rather than a general refund request. Paddle receives and handles the request as Merchant of Record. Submitting a request does not by itself mean that Paddle has approved it; eligibility depends on the purchase, its timing, and whether a waiver for digital content applies.</p>
      <p><a href={PADDLE_BUYER_SUPPORT_URL}>Exercise withdrawal right through Paddle</a></p>
    </section>
    <section><h2>1. Commercial 14-day guarantee</h2><p>We offer a full money-back guarantee for the first paid Syncmemos subscription purchased for an account. Send the request within 14 calendar days after that first subscription transaction. Renewals, later subscriptions, plan changes, and additional seats are not covered by this voluntary guarantee unless we expressly say otherwise.</p></section>
    <section><h2>2. How to request it</h2><p>Use the support or refund link in the Paddle receipt, or visit <a href={PADDLE_BUYER_SUPPORT_URL}>Paddle Buyer Support</a>, follow the refund request route, and provide the requested purchase details. You may also email <a href={`mailto:${seller.email}`}>{seller.email}</a> from the account email about the Syncmemos guarantee and include the Paddle transaction or receipt identifier. Do not send card details. Paddle handles the request and executes any approved refund to the original payment method where possible.</p></section>
    <section><h2>3. Statutory rights</h2><p>The guarantee is additional to, and does not limit, mandatory rights concerning withdrawal, faulty or misdescribed services, or other remedies. Where law or Paddle&apos;s applicable Buyer Terms provides a stronger right, that right applies. An acknowledgement that a withdrawal request was received is not itself a decision that the request is eligible.</p></section>
    <section><h2>4. Cancellation is different</h2><p>Canceling a subscription stops future renewal but does not by itself request a refund or statutory withdrawal. Unless a refund or withdrawal applies, access continues through the paid period. Use the clearly labeled Paddle Buyer Support link in the application to submit a separate request.</p></section>
    <section><h2>5. Refund effects</h2><p>When a full refund is completed, paid access for the refunded transaction may end and the account may return to the Free plan. Processing time after approval depends on Paddle, the payment method, and the financial institution. Chargebacks should not be used as a substitute for contacting support about a genuine issue.</p></section>
  </>;
}

function SwedishRefund({ seller }: { seller: LegalSeller }) {
  return <>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6" aria-labelledby="utova-angerratten">
      <h2 id="utova-angerratten">Utöva lagstadgad ångerrätt</h2>
      <p>Ånger enligt lag är inte samma sak som en frivillig återbetalning. Öppna Paddles köparsupport, identifiera dig med e-postadressen som användes vid köpet och välj alternativet för att ångra köpet i stället för en allmän begäran om återbetalning. Paddle tar emot och handlägger begäran som Merchant of Record. Att skicka en begäran innebär inte i sig att Paddle har godkänt den; rätten beror på köpet, tidpunkten och om ett undantag för digitalt innehåll gäller.</p>
      <p><a href={PADDLE_BUYER_SUPPORT_URL}>Utöva ångerrätten genom Paddle</a></p>
    </section>
    <section><h2>1. Kommersiell 14-dagarsgaranti</h2><p>Vi erbjuder full återbetalning för det första betalda Syncmemos-abonnemanget som köps för ett konto. Begäran ska skickas inom 14 kalenderdagar efter den första abonnemangstransaktionen. Förnyelser, senare abonnemang, planbyten och extra platser omfattas inte av denna frivilliga garanti om vi inte uttryckligen anger annat.</p></section>
    <section><h2>2. Så begär du återbetalning</h2><p>Använd support- eller återbetalningslänken i Paddles kvitto, eller besök <a href={PADDLE_BUYER_SUPPORT_URL}>Paddles köparsupport</a>, följ vägen för att begära återbetalning och lämna de köpuppgifter som efterfrågas. Du kan också mejla <a href={`mailto:${seller.email}`}>{seller.email}</a> från kontots e-postadress om Syncmemos garanti och ange Paddles transaktions- eller kvitto-id. Skicka inga kortuppgifter. Paddle handlägger begäran och genomför en godkänd återbetalning till det ursprungliga betalningssättet när det är möjligt.</p></section>
    <section><h2>3. Lagstadgade rättigheter</h2><p>Garantin gäller utöver och begränsar inte tvingande rättigheter om ånger, felaktiga eller felbeskrivna tjänster eller andra rättsmedel. Om lag eller Paddles tillämpliga köparvillkor ger en starkare rättighet gäller den. Ett mottagningsbevis för en ångerbegäran är inte i sig ett beslut om att begäran är berättigad.</p></section>
    <section><h2>4. Uppsägning är något annat</h2><p>Att säga upp ett abonnemang stoppar framtida förnyelse men är inte i sig en begäran om återbetalning eller lagstadgad ånger. Om återbetalning eller ånger inte gäller fortsätter åtkomsten under den betalda perioden. Använd den tydligt märkta länken till Paddles köparsupport i applikationen för att skicka en separat begäran.</p></section>
    <section><h2>5. Effekter av återbetalning</h2><p>När en full återbetalning har slutförts kan betalåtkomsten för transaktionen upphöra och kontot återgå till Free. Handläggningstiden efter godkännande beror på Paddle, betalningssättet och finansinstitutet. Kortreklamation bör inte användas i stället för att kontakta support om ett verkligt problem.</p></section>
  </>;
}
